version: "3.9"

services:

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:inception
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:inception
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    image: nginx:inception
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    # redis:
    #   build:
    #     context: ./requirements/bonus/redis
    #   contanier_name: redis
    #   image: redis:inception
    #   restart: always
    #   depands_on:
    #   ports:
        # - 

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  inception:
    driver: bridge
